Python 3.7.5 (tags/v3.7.5:5c02a39a0b, Oct 15 2019, 01:31:54) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
>>> help(for)
SyntaxError: invalid syntax
>>> hmwrk =('I will turn in my work on time.')
>>> for i in range(500):
	print(hmwrk)

	
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
I will turn in my work on time.
>>> 
